### ISSUE TITLE
using Modifed and Validate at the same time

### ISSUE THREAD

**Issue by MrAliSalehi** [gengteng/axum-valid#15]
how could I do this:
`Validified<Modified<Json<T>>>` ?
it seems Modified does not validate the data and vice versa

**Comment by gengteng** [comment]
The way Validified works is to first modify the data and then validate the modified data, so it already covers the functionality of Modified. In other words, Validified inherently handles both the "modify" and "validate" phases.
Combinations and nesting like Validified<Modified<T>> are not directly supported right now.
If the provided information does not fully address your specific use case, please feel free to provide a minimal code example demonstrating your intended usage and expected behavior. That would help me better understand the context and see how I could improve the API design to support your scenario.
Please let me know if this helps explain the current capabilities and limitations. I'm happy to discuss further if you have any other questions!

**Comment by MrAliSalehi** [comment]
thanks that worked
